### PR TITLE
Add layout props and refactor

### PR DESCRIPTION
**Pull request by stdavis**
I felt like this simplifies the use of this component by internalizing the container component.

### CODE REVIEW

**Comment by steveoh** [comment]
This does look nice. I made the container optional since I thought there would be occasions where we would want to put the layer selector inside some other element without the icon/expansions. I'm not sure I fully support making the container a requirement to use the layer selector. Even though we have never used the layer selector any other way.

**Comment by steveoh** [comment]
i think breaking changes go as the description not the summary for conventional commits to pick up on them

**Comment by stdavis** [comment]
> I'm not sure I fully support making the container a requirement to use the layer selector.

What about adding a switch that toggles the internal use of the container? Something like this?

```js
LayerSelector.propTypes = {
	...
	wrapWithContainer: PropTypes.bool
}
LayerSelector.defaultProps = {
	wrapWithContainer: true
}
```

**Comment by steveoh** [comment]
Yah I could get behind that. I think another variable name could make it more clear.

**Comment by stdavis** [comment]
`useContainer`
`includeContainer`
?

**Comment by steveoh** [comment]
What about renaming the `LayerSelectorContainer` to something more descriptive, like `ExpandableContainer` and using a prop like `makeExpandable` or `collapse`, or `collapseUntilHover` or something like that???

**Comment by steveoh** [comment]
I wonder if I left out the positioning stuff because of `view.ui.add(selectorNode, 'top-right');`

https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#ui

**Comment by stdavis** [comment]
We re-did this in #29

**Pull request closed without merging**
