### PR TITLE
map-tools re-import and a bunch of grunt task work

### PR DESCRIPTION
**Pull request by stdavis**
This PR:
- re-imports the map-tools package
- grunt task work in jasmine, eslint, babel, sass, e2e, & watch
- cleans up a bunch of package-level stuff that was duplicated at the root

I'm not sure why Travis integration is broken for this repo. I've sent an email to travis support to look into it.

Finally, I'm still not 100% sure that this will scale well with very many packages but I'm hopeful. It sure seems like an easier problem to tackle as opposed to maintaining multiple separate projects.

### CODE REVIEW

**Comment by steveoh** [comment]
a couple of things.

1. default grunt task does not create a _specrunner for the entire project. I would like to be able to test all of the packages easily.
1. grunt test does not find any specs.
1. grunt travis does not work because of grunt test
1. grunt e2e tests failed

**Comment by stdavis** [comment]
> the individual _specrunners have path issues
They run fine on my machine. I wonder if this is a bootstrap/npm install issue.

**Comment by stdavis** [comment]
image

**Comment by steveoh** [comment]
image

**Comment by steveoh** [comment]
you might try lerna clean, then delete your top level node modules and see how it all works.

**Comment by stdavis** [comment]
Getting rid of the `package-lock.json` files for the packages seems to have fixed the problem to me.

I also added lerna bootstrap to the npm install script. Not sure if that's a great idea but I think so.

**Comment by steveoh** [comment]
uninstalling yarn :)

**Pull request merged**
